assets:
  rubygems.yml: zerocracy/home#assets/rubygems.yml
  s3cfg: zerocracy/home#assets/s3cfg
install: |
  sudo apt-get -y update
  sudo gem install pdd
release:
  script: |-
    bundle install
    rake
    rm -rf *.gem
    sed -i "s/1\.0\.snapshot/${tag}/g" lib/xcop/version.rb
    git add lib/xcop/version.rb
    git commit -m "version set to ${tag}"
    gem build xcop.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
  commanders:
  - yegor256
architect:
- yegor256
merge:
  script: |-
    bundle install
    rake
    pdd -f /dev/null
deploy:
  script: |-
    echo "There is nothing to deploy"
    exit -1
